export const dataProduct = [
  {
    id:  '1',
    title: 'BXC',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto1.png',
    description: 'Вытяжное устройство для механической системы вентиляции',
  },
  {
    id:  '2',
    title: 'G2H',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto2.png',
    description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
  },
  {
    id:  '3',
    title: 'GHN',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto3.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '4',
    title: 'TDA',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto4.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '5',
    title: 'BXC',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto1.png',
    description: 'Вытяжное устройство для механической системы вентиляции',
  },
  {
    id:  '6',
    title: 'TDA',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto4.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '7',
    title: 'G2H',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto2.png',
    description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
  },
  {
    id:  '8',
    title: 'GHN',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto3.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '9',
    title: 'TDA',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto4.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '10',
    title: 'TDA',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto4.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '11',
    title: 'G2H',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto2.png',
    description: 'Многофункциональное вытяжное устройство для естественной и гибридной вентиляции',
  },
  {
    id:  '12',
    title: 'GHN',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto3.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
  {
    id:  '13',
    title: 'TDA',
    startPrice: 6848,
    endPrice: 56584,
    startEuro: 77.60,
    endEuro: 643.86,
    image: '/products/foto4.png',
    description: 'Вытяжное устройство с датчиком присутствия',
  },
]